### ISSUE TITLE
Fix UI

### ISSUE THREAD

**Issue by hungle00** [hungle00/flask-mini-pinterest#5]
- Sửa lại navbar: đưa link _new pin_ lên navbar. Cần hiển thị:
    - Chưa login: Link đến _login_ và _signup_
    - Đã Login: Link đến _new pin, username, link profile user, logout_
- Trang profile user chứa thông tin: username, email, fake avatar ( cột trái), pin của user đó ( cột phải)  
- Sửa lại trang show: Cột trái chứa ảnh, title, button edit, delete, like, pin, cột phải để show ảnh tương tự
- Sửa lại trang index, bỏ dòng helo vs mấy cái button, thay bằng thanh search, tham khảo UI [font awesome](https://fontawesome.com/icons)

Update 2/3:
- Làm form search rông hơn, đồng nhất độ rộng form login và signup
- Fix design trang index để hiển thị nhiều ảnh hơn, bỏ nút like, dislike,  cho nút pin lên cùng hàng title....
- Trang show pin: nếu user chưa login hoặc user k phải ng tạo pin thì hiển thị icon like và pin cho đỡ trống.
- _Ưu tiên xong 3 task trên trc rồi mới thêm profile user_

**Comment by evil-nerver-die** [comment]
- xem lại flash message
- sign up xong redirect về index
- fix navbar khi thu nhỏ cửa sổ trình duyệt tham khảo https://www.youtube.com/watch?v=qNifU_aQRio&t=405s&ab_channel=AdrianTwarog
-
